Name:           perl-App-AudioTuber
Version:        0
Release:        1%{?dist}
Summary:        App::AudioTuber Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/App-AudioTuber/
Source0:        http://www.cpan.org/modules/by-module/App/App-AudioTuber-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(FFmpeg::Command)
BuildRequires:  perl(File::Basename)
BuildRequires:  perl(File::Which)
BuildRequires:  perl(Getopt::Long)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(MP3::Info)
BuildRequires:  perl(Pod::Select)
BuildRequires:  perl(Test::Compile)
BuildRequires:  perl(Test::More) >= 0.47
BuildRequires:  perl(Test::Perl::Critic)
Requires:       perl(FFmpeg::Command)
Requires:       perl(File::Basename)
Requires:       perl(File::Which)
Requires:       perl(Getopt::Long)
Requires:       perl(MP3::Info)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
If the MP3 file contains embedded cover art, it will be used a still image
in the video. An image file can also be provided with command line options.
If no cover art is available, the video will be plain black with the
caption overlaid.

%prep
%setup -q -n App-AudioTuber-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Apr 26 2019 Jonathan Gazeley <me@jonathangazeley.com> 0-1
- Specfile autogenerated by cpanspec 1.78.
